INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost) VALUES (N'Mass Effect 2', N'От создателей Star Wars®: Knights of the Old Republic™, Dragon Age: Origins™ и Mass Effect™ встречайте второй тёмный эпизод эпичной трилогии Mass Effect.
Через два года после того, как капитан Шепард отразил вторжение Жнецов, стремившихся уничтожить всю органическую жизнь во вселенной, у человечества появился новый враг. На окраинах обитаемого космоса кто-то постепенно уничтожает людские колонии. Чтобы остановить надвигающуюся угрозу, Шепарду предстоит сотрудничать с Цербером - безжалостной террористической организацией, провозглашающей выживание человечества любой ценой.', N'Bioware', N'Sci-Fi action shooter', N'EA games', 20);
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost) VALUES (N'Mass Effect', N'В роли капитана Шепарда, возглавляющего отряд элитных бойцов, вам предстоит отправиться по всей галактике в эпическое, полное приключений путешествие.

Вам откроется нависшая над миром опасность, затаившаяся и ждущая своего часа с незапамятных времен. Чтобы спасти цивилизацию, вам придется сразиться с предателем Сареном и его смертоносной армией. Судьба всего живого зависит от вас и ваших действий!
', N'Bioware', N'Sci-Fi action shooter', N'EA games', 20);
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost) VALUES (N'Divinity Original Sin 2', N'Божественный мертв. Пустота надвигается. А внутри вас просыпаются доселе неведомые силы. Битва за божественность началась. Тщательно выбирайте, кому верить: в эти непростые времена тьма может скрываться в каждом сердце.', N'Larian Studios', N'Tactical RPG game', N'Larian', 10);
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost) VALUES ( N'Nier: Automata', N'NieR: Automata tells the story of androids 2B, 9S and A2 and their battle to reclaim the machine-driven dystopia overrun by powerful machines.

Humanity has been driven from the Earth by mechanical beings from another world. In a final effort to take back the planet, the human resistance sends a force of android soldiers to destroy the invaders. Now, a war between machines and androids rages on... A war that could soon unveil a long-forgotten truth of the world.', N'Platinum games', N'JRPG Slasher', N'EA games', 20);
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost) VALUES (N'The Elder Scrolls V: Skyrim', N'Winner of more than 200 Game of the Year Awards, Skyrim Special Edition brings the epic fantasy to life in stunning detail. The Special Edition includes the critically acclaimed game and add-ons with all-new features like remastered art and effects, volumetric god rays, dynamic depth of field, screen-space reflections, and more. Skyrim Special Edition also brings the full power of mods to the PC and consoles. New quests, environments, characters, dialogue, armor, weapons and more – with Mods, there are no limits to what you can experience.', N'Bethesda', N'Action RPG', N'Bethesda', 20);
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost) VALUES (N'METAL GEAR SOLID V: PHANTOM PAIN', N'Спустя девять лет после событий игры «MGSV: GROUND ZEROES» и падения Главной базы «Большой босс» Снейк выходит из комы. На дворе 1984 год. На фоне холодной войны продолжается глобальное обострение ядерного кризиса. Движимый местью, Снейк создает новую частную армию и возвращается на поле боя в поисках тайной группы XOF.

', N'Konami, Kojima Productins', N'Tactical shooter', N'Konami', 20);
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost) VALUES ( N'Divinity Original Sin', N'Gather your party and get back to the roots of great RPG gameplay. Discuss your decisions with companions; fight foes in turn-based combat; explore an open world and interact with everything and everyone you see.

You take on the role of a young Source Hunter: your job is to rid the world of those who use the foulest of magics. Embarking on what should have been a routine murder investigation, you find yourself in the middle of a plot that threatens to destroy the very fabric of time.
', N'Larian Studios', N'Tactical RPG game', N'Larian', 10);
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost) VALUES (N'Mass Effect 3', N'Земля горит. Жнецы берут верх, и другие цивилизации отступают перед их натиском. Капитан Шепард! Ведите союзников в последний бой, чтобы спасти человечество от этих кошмарных машин. Заручитесь помощью, создавайте новые альянсы, но будьте готовы расстаться, когда придет время. В этом сражении могут потребоваться величайшие жертвы. Настал час, когда капитан Шепард должен отвоевать галактику.', N'Bioware', N'Sci-Fi action shooter', N'EA games', 20);
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost) VALUES (N'Portal 2', N'В Portal 2 вы откроете для себя инновационный геймплей, сюжет и музыку, которая помогла оригиналу заработать более 70 наград в игровой индустрии, а также создала целый культ имени самой себя.', N'valve', N'Pazzle game', N'valve', 2);
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost) VALUES (N'Witcher 3: Wild Hunt', N'«Ведьмак 3: Дикая Охота» — это сюжетная ролевая игра с открытым миром. Её действие разворачивается в поразительной волшебной вселенной, и любое ваше решение может повлечь за собой серьёзные последствия. Вы играете за профессионального охотника на монстров Геральта из Ривии, которому поручено найти Дитя предназначения в огромном мире, полном торговых городов, пиратских островов, опасных горных перевалов и заброшенных пещер.', N'CD PROJECT RED', N'Action RPG', N'CD PROJECT', 15);
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost) VALUES (N'Portal', N'Portal™ — новая игра от Valve для одного игрока. Portal, действие которого происходит в загадочных лабораториях компании Aperture, был назван одной из самых новаторских игр современности и предлагает вниманию игрока множество часов непохожей ни на что головоломки.', N'Valve', N'Pazzle game', N'Valve', 2);
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost) VALUES (N'Mass Effect: Andromeda', N'Mass Effect™: Andromeda вы окажетесь в галактике Андромеды, далеко за пределами Млечного Пути. Там придется сражаться на враждебной территории в роли Первопроходца — главы команды опытных, готовых постоять за себя профессионалов. Это — новая глава в истории, и только от выбора игрока зависит судьба человечества.', N'Bioware', N'Sci-Fi action shooter', N'EA games', 20);