create table Products.Games
(
    GameId          int identity
        constraint PK_GameKey
            primary key,
    Title           nvarchar(128)                    not null,
    Description     nvarchar(MAX) default 'The game hasn`t description',
    Studio          nvarchar(64)                     not null,
    Genre           nvarchar(32)   default 'UNKNOWN' not null,
    Publisher       nvarchar(64)   default 'INDIE'   not null,
    Cost            int           default 0         not null,
    PreviewImageUrl nvarchar(128)  default ''
)
go



INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'Prey', N'Действие Prey происходит в 2032 году. Вы обнаруживаете себя на лунной орбите, на борту космической станции «Талос-1». Эксперимент, в котором вы участвовали, должен был навсегда изменить человеческую расу, но привел к катастрофическим последствиям. Станцию захватили враждебные пришельцы, которые теперь ведут на вас охоту. Раскрывая мрачные тайны «Талоса» и собственного прошлого, вам предстоит выживать, полагаясь на подручные средства, собственную смекалку, оружие и сверхспособности. Судьба «Талоса-1» и всех, кто находится на борту, — в ваших руках.', N'Arcane Studios', N'Sci-Fi Shooter', N'Bethesda', 25, N'https://cdn.cloudflare.steamstatic.com/steam/apps/480490/header.jpg?t=1594910513');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'Mass Effect 2', N'От создателей Star Wars®: Knights of the Old Republic™, Dragon Age: Origins™ и Mass Effect™ встречайте второй тёмный эпизод эпичной трилогии Mass Effect.
Через два года после того, как капитан Шепард отразил вторжение Жнецов, стремившихся уничтожить всю органическую жизнь во вселенной, у человечества появился новый враг. На окраинах обитаемого космоса кто-то постепенно уничтожает людские колонии. Чтобы остановить надвигающуюся угрозу, Шепарду предстоит сотрудничать с Цербером - безжалостной террористической организацией, провозглашающей выживание человечества любой ценой.', N'Bioware', N'Sci-Fi action shooter', N'EA games', 20, N'https://cdn.cloudflare.steamstatic.com/steam/apps/24980/header.jpg?t=1591856004');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'Mass Effect', N'В роли капитана Шепарда, возглавляющего отряд элитных бойцов, вам предстоит отправиться по всей галактике в эпическое, полное приключений путешествие.

Вам откроется нависшая над миром опасность, затаившаяся и ждущая своего часа с незапамятных времен. Чтобы спасти цивилизацию, вам придется сразиться с предателем Сареном и его смертоносной армией. Судьба всего живого зависит от вас и ваших действий!
', N'Bioware', N'Sci-Fi action shooter', N'EA games', 20, N'https://cdn.cloudflare.steamstatic.com/steam/apps/17460/header.jpg?t=1573056911');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'Nier: Automata', N'NieR: Automata tells the story of androids 2B, 9S and A2 and their battle to reclaim the machine-driven dystopia overrun by powerful machines.

Humanity has been driven from the Earth by mechanical beings from another world. In a final effort to take back the planet, the human resistance sends a force of android soldiers to destroy the invaders. Now, a war between machines and androids rages on... A war that could soon unveil a long-forgotten truth of the world.', N'Platinum games', N'JRPG Slasher', N'EA games', 20, N'https://cdn.cloudflare.steamstatic.com/steam/apps/524220/header.jpg?t=1601026299');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'The Elder Scrolls V: Skyrim', N'Winner of more than 200 Game of the Year Awards, Skyrim Special Edition brings the epic fantasy to life in stunning detail. The Special Edition includes the critically acclaimed game and add-ons with all-new features like remastered art and effects, volumetric god rays, dynamic depth of field, screen-space reflections, and more. Skyrim Special Edition also brings the full power of mods to the PC and consoles. New quests, environments, characters, dialogue, armor, weapons and more – with Mods, there are no limits to what you can experience.', N'Bethesda', N'Action RPG', N'Bethesda', 20, N'https://cdn.cloudflare.steamstatic.com/steam/apps/489830/header.jpg?t=1590515887');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'METAL GEAR SOLID V: PHANTOM PAIN', N'Спустя девять лет после событий игры «MGSV: GROUND ZEROES» и падения Главной базы «Большой босс» Снейк выходит из комы. На дворе 1984 год. На фоне холодной войны продолжается глобальное обострение ядерного кризиса. Движимый местью, Снейк создает новую частную армию и возвращается на поле боя в поисках тайной группы XOF.

', N'Konami, Kojima Productins', N'Tactical shooter', N'Konami', 20, N'https://cdn.cloudflare.steamstatic.com/steam/apps/287700/header.jpg?t=1591740509');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'Divinity Original Sin', N'Gather your party and get back to the roots of great RPG gameplay. Discuss your decisions with companions; fight foes in turn-based combat; explore an open world and interact with everything and everyone you see.

You take on the role of a young Source Hunter: your job is to rid the world of those who use the foulest of magics. Embarking on what should have been a routine murder investigation, you find yourself in the middle of a plot that threatens to destroy the very fabric of time.
', N'Larian Studios', N'Tactical RPG game', N'Larian', 10, N'https://cdn.cloudflare.steamstatic.com/steam/apps/373420/header.jpg?t=1589968419');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'Mass Effect 3', N'Земля горит. Жнецы берут верх, и другие цивилизации отступают перед их натиском. Капитан Шепард! Ведите союзников в последний бой, чтобы спасти человечество от этих кошмарных машин. Заручитесь помощью, создавайте новые альянсы, но будьте готовы расстаться, когда придет время. В этом сражении могут потребоваться величайшие жертвы. Настал час, когда капитан Шепард должен отвоевать галактику.', N'Bioware', N'Sci-Fi action shooter', N'EA games', 20, N'https://cdn.cloudflare.steamstatic.com/steam/apps/1238020/header.jpg?t=1598621625');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'Portal 2', N'В Portal 2 вы откроете для себя инновационный геймплей, сюжет и музыку, которая помогла оригиналу заработать более 70 наград в игровой индустрии, а также создала целый культ имени самой себя.', N'valve', N'Pazzle game', N'valve', 2, N'https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg?t=1587582232');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'Witcher 3: Wild Hunt', N'«Ведьмак 3: Дикая Охота» — это сюжетная ролевая игра с открытым миром. Её действие разворачивается в поразительной волшебной вселенной, и любое ваше решение может повлечь за собой серьёзные последствия. Вы играете за профессионального охотника на монстров Геральта из Ривии, которому поручено найти Дитя предназначения в огромном мире, полном торговых городов, пиратских островов, опасных горных перевалов и заброшенных пещер.', N'CD PROJECT RED', N'Action RPG', N'CD PROJECT', 15, N'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header_russian.jpg?t=1598535144');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'Portal', N'Portal™ — новая игра от Valve для одного игрока. Portal, действие которого происходит в загадочных лабораториях компании Aperture, был назван одной из самых новаторских игр современности и предлагает вниманию игрока множество часов непохожей ни на что головоломки.', N'Valve', N'Pazzle game', N'Valve', 2, N'https://cdn.cloudflare.steamstatic.com/steam/apps/400/header.jpg?t=1587581981');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'Mass Effect: Andromeda', N'Mass Effect™: Andromeda вы окажетесь в галактике Андромеды, далеко за пределами Млечного Пути. Там придется сражаться на враждебной территории в роли Первопроходца — главы команды опытных, готовых постоять за себя профессионалов. Это — новая глава в истории, и только от выбора игрока зависит судьба человечества.', N'Bioware', N'Sci-Fi action shooter', N'EA games', 20, N'https://cdn.cloudflare.steamstatic.com/steam/apps/1238000/header.jpg?t=1598995968');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'Divinity Original Sin 2', N'Божественный мертв. Пустота надвигается. А внутри вас просыпаются доселе неведомые силы. Битва за божественность началась. Тщательно выбирайте, кому верить: в эти непростые времена тьма может скрываться в каждом сердце.', N'Larian Studios', N'Tactical RPG game', N'Larian', 10, N'https://cdn.cloudflare.steamstatic.com/steam/apps/435150/header.jpg?t=1592914193');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'Dragon Age: Origins', N'От создателей Mass Effect и Baldur’s Gate встречайте эпическую сагу Dragon Age: Origins.
Вам предстоит взять роль Серого Стража, одного из последних представителей когда то легендарного ордена. Когда над миром нависло древнее зло, а королевство охвачено гражданской войной, нужен герой способный объединить раздробленные земли и уничтожить Архидемона раз и на всегда.', N'Bioware', N'RPG', N'EA games', 25, N'https://cdn.cloudflare.steamstatic.com/steam/apps/17450/header.jpg?t=1594921078');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'Dragon Age 2', N'Вы — Хоук, и вы готовы пройти путь от беженца до Защитника Киркволла. Обретите влияние и примите участие в эпических баталиях, которые определят судьбу цивилизации. Ваше восхождение к власти начинается сейчас. Кем вас запомнит история?', N'Bioware', N'RPG', N'EA games', 25, N'https://cdn.cloudflare.steamstatic.com/steam/apps/1238040/header.jpg?t=1598621695');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'Dragon Age: Inqusition', N'Когда небеса разверзаются и исторгают хаос, миру нужны герои. Станьте спасителем Тедаса в игре «Dragon Age: Инквизиция - издание Игра года». Вы — Инквизитор, и вам предстоит спасти мир от него самого. Но этот путь будет вымощен тяжелыми решениями. Тедас — земля раздоров. Стороны не перестают враждовать друг с другом, даже когда в мир рекой текут демоны. А что же вы? Вы со своим отрядом — единственные, кто может удержать весь свет на краю пропасти. Вам предстоит возглавить всех... или погибнуть.', N'Bioware', N'RPG', N'EA games', 55, N'https://cdn.cloudflare.steamstatic.com/steam/apps/1222690/header.jpg?t=1598995320');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'Among us', N'Play with 4-10 player online or via local WiFi as you attempt to prepare your spaceship for departure, but beware as one or more random players among the Crew are Impostors bent on killing everyone!  Originally created as a party game, we recommend playing with friends at a LAN party or online using voice chat. Enjoy cross-platform play between Android, iOS and PC.', N'Innersloth', N'Mafia', N'Innersloth', 2, N'https://cdn.cloudflare.steamstatic.com/steam/apps/945360/header.jpg?t=1598556351');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'CYBERPUNK 2077', N'Cyberpunk 2077 — приключенческая ролевая игра, действие которой происходит в мегаполисе Найт-Сити, где власть, роскошь и модификации тела ценятся выше всего. Вы играете за V, наёмника в поисках устройства, позволяющего обрести бессмертие. Вы сможете менять киберимпланты, навыки и стиль игры своего персонажа, исследуя открытый мир, где ваши поступки влияют на ход сюжета и всё, что вас окружает.', N'CD PROJEKT RED', N'Action RPG Shooter', N'CD PROJEKT RED', 60, N'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg?t=1600446313');
INSERT INTO GameCentral.Products.Games (Title, Description, Studio, Genre, Publisher, Cost, PreviewImageUrl) VALUES (N'STAR WARS™: Squadrons', N'Освойте искусство сражений на звёздных истребителях в реалистичном симуляторе полёта STAR WARS™: Squadrons. Пристегните ремень и ощутите прилив адреналина в крови, участвуя в многопользовательских воздушных схватках от первого лица со своей эскадрильей. Новым пилотам предстоит полетать как за Новую Республику, так и за Империю, а также принять участие в стратегических космических битвах 5 на 5. Модифицируйте свой звёздный истребитель и выбирайте участников эскадрильи, чтобы они соответствовали вашему стилю игры и помогли сокрушить противника. Пилоты будут побеждать в команде и выполнять задания как на уже знакомых, так и на совершенно новых полях сражений, включая газовый гигант Явин-Прайм и разрушенный спутник Галитан.', N'MOTIVE', N'Flight Simulator', N'EA games', 50, N'https://cdn.cloudflare.steamstatic.com/steam/apps/1222730/header.jpg?t=1601525711');

